vector_statistics: vector_statistics.o
	g++ -o vector_statistics vector_statistics.o

vector_statistics.o: vector_statistics.cc
	g++ -c vector_statistics.cc

clear:
	rm *.o

clear1:
	rm vector_statistics
